CREATE DATABASE 8_AM_BATCH;

USE 8_AM_BATCH;

CREATE TABLE DEPARTMENT(
DEPT_ID INT PRIMARY KEY AUTO_INCREMENT,
DEPT_NAME VARCHAR (100)NOT NULL UNIQUE
);

CREATE TABLE EMPLOYEE(
EMP_ID INT PRIMARY KEY AUTO_INCREMENT,
FIRST_NAME VARCHAR(50)NOT NULL UNIQUE,
LAST_NAME VARCHAR(100),
EMAIL_ID VARCHAR (100) UNIQUE,
BIRTH_DATE DATE,
GENDER ENUM("MALE","FEMALE","OTHER") DEFAULT "OTHER",
SALARY DECIMAL(10,2) DEFAULT 30000 CHECK (SALARY>0),
DEPT_ID INT,
foreign key (DEPT_ID) references DEPARTMENT(DEPT_ID)
);

INSERT INTO DEPARTMENT(DEPT_NAME)
VALUES
("FINANCE"),("IT"),("MARKETING");

SELECT * FROM DEPARTMENT;

INSERT INTO EMPLOYEE(
FIRST_NAME,LAST_NAME,GENDER,DOB,EMAIL,SALARY,DEPT_ID)
VALUES
("SHWETA","GHOTEKAR","FEMALE","1995-06-13","SHWETA@GMAIL.COM","30000","1");

SELECT * FROM EMPLOYEE;

CREATE TABLE STUDENTS(
STUD_ID INT PRIMARY KEY AUTO_INCREMENT,
FIRST_NAME VARCHAR(50)NOT NULL UNIQUE,
LAST_NAME VARCHAR(100)UNIQUE ,
EMAIL_ID VARCHAR(100) unique,
DOB DATE,
GENDER ENUM ("MALE","FEMAE","OTHER")default"OTHER"
);

CREATE TABLE COURSE(
COURSE_ID INT PRIMARY KEY AUTO_INCREMENT,
COURSE_NAME  VARCHAR(100) UNIQUE,
CREDITS INT CHECK (CREDITS>0)
);


CREATE TABLE ENROLLMENT(
ENROLL_ID INT PRIMARY KEY AUTO_INCREMENT,
STUDENT_ID INT,
COURSE_ID INT,
ENROLL_DATE DATE DEFAULT "2025-05-27",
foreign key (STUDENT_ID) references STUDENT (STUDENT_ID)
);

CREATE TABLE PRODUCT(
PROD_ID INT PRIMARY KEY AUTO_INCREMENT,
PROD_NAME VARCHAR(100) UNIQUE,
CATEGORY VARCHAR(100),
PRICE DECIMAL(10,2) CHECK(PRICE>0),
STOCK_QUANTITY INT DEFAULT 0
);















